"""change activity scheduled date to timestamp

Revision ID: c995db6b0e70
Revises: 049496d52f0a
Create Date: 2026-08-28 15:07:47.468077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c995db6b0e70'
down_revision: Union[str, Sequence[str], None] = '049496d52f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_otps_phone'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    op.alter_column('activities', 'scheduled_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key('fk_cfa_kfs_official', 'community_forest_associations', 'users', ['kenya_forest_service_official_id'], ['user_id'], use_alter=True)
    op.create_foreign_key('fk_users_cfa', 'users', 'community_forest_associations', ['community_forest_association_id'], ['community_forest_association_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_cfa', 'users', type_='foreignkey')
    op.drop_constraint('fk_cfa_kfs_official', 'community_forest_associations', type_='foreignkey')
    op.alter_column('activities', 'scheduled_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_otps_pkey'))
    )
    op.create_index(op.f('ix_password_reset_otps_phone'), 'password_reset_otps', ['phone'], unique=False)
    # ### end Alembic commands ###
