"""add permit timestamps

Revision ID: da1d9730f930
Revises: f5e724c441e3
Create Date: 2026-08-30 15:20:19.976837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da1d9730f930'
down_revision: Union[str, Sequence[str], None] = 'f5e724c441e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_otps_phone'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    op.alter_column('forest_zones', 'community_forest_association_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('permits', 'forest_zone_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('permits', 'resource_price_at_purchase',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_permits_forest_zone_id'), 'permits', ['forest_zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permits_forest_zone_id'), table_name='permits')
    op.alter_column('permits', 'resource_price_at_purchase',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('permits', 'forest_zone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('forest_zones', 'community_forest_association_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_otps_pkey'))
    )
    op.create_index(op.f('ix_password_reset_otps_phone'), 'password_reset_otps', ['phone'], unique=False)
    # ### end Alembic commands ###
